name: CMake Build

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # Install dependencies and build on Linux
      - name: Install dependencies (Linux)
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential cmake

      - name: Configure CMake (Linux)
        if: runner.os == 'Linux'
        run: cmake -S . -B build -DCMAKE_BUILD_TYPE=Release

      - name: Build with CMake (Linux)
        if: runner.os == 'Linux'
        run: cmake --build build --config Release

      # Install dependencies and build on Windows
      - name: Set up MSVC (Windows)
        if: runner.os == 'Windows'
        uses: ilammy/msvc-dev-cmd@v1

      - name: Configure CMake (Windows)
        if: runner.os == 'Windows'
        run: cmake -S . -B build -G "Visual Studio 17 2022" -A x64

      - name: Build with CMake (Windows)
        if: runner.os == 'Windows'
        run: cmake --build build --config Release
